# Generated by Django 3.2 on 2024-01-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_auto_20240122_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_devolucion',
            new_name='fecha_devoluciones',
        ),
    ]
