# Generated by Django 3.2 on 2024-01-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0004_rename_fecha_devolucion_prestamo_fecha_devoluciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devoluciones',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
