# Generated by Django 3.2 on 2024-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0009_auto_20240122_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucio',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
