# Generated by Django 3.2 on 2024-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0010_auto_20240122_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
    ]
