# Generated by Django 3.2 on 2024-01-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0012_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
