# Generated by Django 3.2 on 2024-01-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0013_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True),
        ),
    ]
