# Generated by Django 3.2 on 2024-01-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0014_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion',
        ),
    ]
