# Generated by Django 3.2 on 2024-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0015_remove_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
