# Generated by Django 3.2 on 2024-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0017_auto_20240122_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
    ]
