# Generated by Django 3.2 on 2024-01-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0019_remove_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
